# Generated by Django 2.1.4 on 2019-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
